# Data Cleaning and Initial Analysis

## 1. Project Context

## 2. Dataset Creation

The dataset used in this project was synthetically created to simulate a realistic sales dataset from a small retail business.

The business sells clothing, accessories, footwear, and outerwear through different sales channels, including physical store, online store, and marketplace.

The raw dataset intentionally includes common data quality issues found in real business spreadsheets, such as:

- duplicated rows;
- missing customer, city, price, and discount values;
- inconsistent product names;
- inconsistent category names;
- inconsistent sales channel labels;
- invalid quantities;
- invalid discount percentages;
- mixed date formats.

These issues will be identified, documented, and cleaned in the next phases of the project.

In [1]:
from pathlib import Path

import numpy as np
import pandas as pd

In [3]:
PROJECT_ROOT = Path.cwd().parent

DATA_RAW_PATH = PROJECT_ROOT / "data" / "raw"
DATA_PROCESSED_PATH = PROJECT_ROOT / "data" / "processed"
FIGURES_PATH = PROJECT_ROOT / "reports" / "figures"

DATA_RAW_PATH.mkdir(parents=True, exist_ok=True)
DATA_PROCESSED_PATH.mkdir(parents=True, exist_ok=True)
FIGURES_PATH.mkdir(parents=True, exist_ok=True)

print(PROJECT_ROOT)

C:\Users\Joalyson Lima\OneDrive\Área de Trabalho\small-business-sales-analysis

In [4]:
np.random.seed(42)

n_rows = 5000

products = {
    "Classic T-Shirt": {"category": "Clothing", "price": 18.99},
    "Denim Jeans": {"category": "Clothing", "price": 49.99},
    "Hoodie": {"category": "Clothing", "price": 39.99},
    "Leather Belt": {"category": "Accessories", "price": 24.99},
    "Baseball Cap": {"category": "Accessories", "price": 14.99},
    "Canvas Tote Bag": {"category": "Accessories", "price": 19.99},
    "Running Socks": {"category": "Footwear", "price": 9.99},
    "Sneakers": {"category": "Footwear", "price": 64.99},
    "Winter Jacket": {"category": "Outerwear", "price": 89.99},
    "Rain Coat": {"category": "Outerwear", "price": 74.99},
}

cities = [
    "London", "Manchester", "Birmingham", "Bristol", "Cardiff",
    "Liverpool", "Leeds", "Glasgow", "Edinburgh"
]

sales_channels = ["Physical Store", "Online Store", "Marketplace"]
payment_methods = ["Debit Card", "Credit Card", "PayPal", "Cash", "Bank Transfer"]

customer_first_names = [
    "James", "Olivia", "Liam", "Emma", "Noah", "Amelia", "William",
    "Sophia", "Lucas", "Isabella", "Mason", "Mia", "Ethan", "Charlotte"
]

customer_last_names = [
    "Smith", "Johnson", "Brown", "Taylor", "Wilson", "Davies",
    "Evans", "Thomas", "Roberts", "Walker"
]

date_range = pd.date_range(start="2025-01-01", end="2025-12-31", freq="D")

rows = []

for i in range(1, n_rows + 1):
    product_name = np.random.choice(list(products.keys()))
    product_info = products[product_name]
    
    quantity = np.random.choice([1, 1, 1, 2, 2, 3, 4, 5])
    unit_price = product_info["price"]
    discount = np.random.choice([0, 0, 0, 5, 10, 15, 20])
    
    customer_name = (
        np.random.choice(customer_first_names) 
        + " " 
        + np.random.choice(customer_last_names)
    )
    
    row = {
        "order_id": f"ORD-{1000 + i}",
        "order_date": np.random.choice(date_range),
        "customer_id": f"CUST-{np.random.randint(100, 250)}",
        "customer_name": customer_name,
        "city": np.random.choice(cities),
        "product_name": product_name,
        "category": product_info["category"],
        "quantity": quantity,
        "unit_price": unit_price,
        "discount_percent": discount,
        "sales_channel": np.random.choice(sales_channels, p=[0.45, 0.40, 0.15]),
        "payment_method": np.random.choice(payment_methods),
    }
    
    rows.append(row)

sales_df = pd.DataFrame(rows)

sales_df.head()

,order_id,order_date,customer_id,customer_name,city,product_name,category,quantity,unit_price,discount_percent,sales_channel,payment_method
0,ORD-1001,2025-07-08,CUST-120,Mason Thomas,Leeds,Running Socks,Footwear,2,9.99,10,Physical Store,PayPal
1,ORD-1002,2025-05-11,CUST-249,Sophia Thomas,Cardiff,Sneakers,Footwear,2,64.99,5,Marketplace,Cash
2,ORD-1003,2025-11-10,CUST-121,Noah Smith,Edinburgh,Canvas Tote Bag,Accessories,1,19.99,5,Physical Store,PayPal
3,ORD-1004,2025-12-30,CUST-154,Mia Brown,Bristol,Rain Coat,Outerwear,5,74.99,5,Online Store,PayPal
4,ORD-1005,2025-06-16,CUST-117,Noah Roberts,Bristol,Baseball Cap,Accessories,1,14.99,20,Marketplace,Credit Card

In [5]:
sales_raw = sales_df.copy()

# 1. Add duplicated rows
duplicated_rows = sales_raw.sample(12, random_state=42)
sales_raw = pd.concat([sales_raw, duplicated_rows], ignore_index=True)

# 2. Add missing values
sales_raw.loc[sales_raw.sample(8, random_state=1).index, "customer_name"] = np.nan
sales_raw.loc[sales_raw.sample(6, random_state=2).index, "city"] = np.nan
sales_raw.loc[sales_raw.sample(5, random_state=3).index, "discount_percent"] = np.nan
sales_raw.loc[sales_raw.sample(4, random_state=4).index, "unit_price"] = np.nan

# 3. Add inconsistent product names
sales_raw.loc[sales_raw.sample(5, random_state=5).index, "product_name"] = " classic t-shirt "
sales_raw.loc[sales_raw.sample(5, random_state=6).index, "product_name"] = "HOODIE"
sales_raw.loc[sales_raw.sample(5, random_state=7).index, "product_name"] = "sneakers "

# 4. Add inconsistent category formatting
sales_raw.loc[sales_raw.sample(5, random_state=8).index, "category"] = "clothing"
sales_raw.loc[sales_raw.sample(5, random_state=9).index, "category"] = " ACCESSORIES "
sales_raw.loc[sales_raw.sample(5, random_state=10).index, "category"] = "footwear"

# 5. Add inconsistent sales channel values
sales_raw.loc[sales_raw.sample(5, random_state=11).index, "sales_channel"] = "online"
sales_raw.loc[sales_raw.sample(5, random_state=12).index, "sales_channel"] = "Online store "
sales_raw.loc[sales_raw.sample(5, random_state=13).index, "sales_channel"] = "MARKETPLACE"

# 6. Add invalid numerical values
sales_raw.loc[sales_raw.sample(3, random_state=14).index, "quantity"] = -1
sales_raw.loc[sales_raw.sample(3, random_state=15).index, "quantity"] = 0
sales_raw.loc[sales_raw.sample(3, random_state=16).index, "discount_percent"] = 150
sales_raw.loc[sales_raw.sample(3, random_state=17).index, "discount_percent"] = -10

# 7. Add different date formats
sales_raw["order_date"] = pd.to_datetime(sales_raw["order_date"])

sample_date_idx_1 = sales_raw.sample(10, random_state=18).index
sample_date_idx_2 = sales_raw.sample(10, random_state=19).index

sales_raw.loc[sample_date_idx_1, "order_date"] = sales_raw.loc[sample_date_idx_1, "order_date"].dt.strftime("%d/%m/%Y")
sales_raw.loc[sample_date_idx_2, "order_date"] = sales_raw.loc[sample_date_idx_2, "order_date"].dt.strftime("%Y/%m/%d")

# 8. Convert remaining dates to string format
sales_raw["order_date"] = sales_raw["order_date"].astype(str)

sales_raw.head()

,order_id,order_date,customer_id,customer_name,city,product_name,category,quantity,unit_price,discount_percent,sales_channel,payment_method
0,ORD-1001,2025-07-08,CUST-120,Mason Thomas,Leeds,Running Socks,Footwear,2,9.99,10.0,Physical Store,PayPal
1,ORD-1002,2025-05-11,CUST-249,Sophia Thomas,Cardiff,Sneakers,Footwear,2,64.99,5.0,Marketplace,Cash
2,ORD-1003,2025-11-10,CUST-121,Noah Smith,Edinburgh,Canvas Tote Bag,Accessories,1,19.99,5.0,Physical Store,PayPal
3,ORD-1004,2025-12-30,CUST-154,Mia Brown,Bristol,Rain Coat,Outerwear,5,74.99,5.0,Online Store,PayPal
4,ORD-1005,2025-06-16,CUST-117,Noah Roberts,Bristol,Baseball Cap,Accessories,1,14.99,20.0,Marketplace,Credit Card

In [6]:
raw_file_path = DATA_RAW_PATH / "small_business_sales_raw.csv"

sales_raw.to_csv(raw_file_path, index=False)

print(f"Raw dataset saved at: {raw_file_path}")
print(f"Dataset shape: {sales_raw.shape}")

Raw dataset saved at: C:\Users\Joalyson Lima\OneDrive\Área de Trabalho\small-business-sales-analysis\data\raw\small_business_sales_raw.csv
Dataset shape: (5012, 12)